### ISSUE TITLE
Candi Hosted Documentation

### ISSUE THREAD

**Issue by isogram** [golangid/candi-docs#6]
Hi guys, can we have hosted documentation instead of running it locally?

What if we serve this repo to a free hosting service like Vercel? Maybe it's going to be https://candi-documentation.vercel.app,  https://candi-docs.vercel.app, or something.

I've tested it using the forked repo, and it's working. You guys can take a look at https://candi.vercel.app/#/.
I want to connect it to the original repository so every time the branch gets updated, it will automatically be there.

There are some options we can approach here.
1. Someone creating Vercel account by using this organization's "Admin" email. Then I can offer you help to set it up.
2. Give my account permission regarding the Vercel app integration to this repo. I've already asked for it.
![image](https://user-images.githubusercontent.com/3049864/192313125-a8deb995-c599-454a-8e4d-0e58222057e7.png)
3. Using another hosting service
4. Dismiss my input 😔

What do you think? I need your advice. 

@golangid/candi-reviewer

**Comment by ibnu-assaumi** [comment]
thanks @isogram 
https://candi-docs-isogram.vercel.app/

**Comment by agungdwiprasetyo** [comment]
dear @isogram I've added you as an admin in this repository, kindly check, thanks! 😬

**Comment by isogram** [comment]
Whoops... I'm sorry for the inconvenience. I got this error when tried to connect the repo
![image](https://user-images.githubusercontent.com/3049864/192575709-034ce1f9-34fe-4451-aeef-54b0193a36b2.png)
Seems it cannot be connected unless we pay for it.
Maybe in the future, we can ask Vercel to support Candi and give us their pro plan. 😁

Let me stick to using the forked repo for hosted documentation. I'll keep my forked repo in sync with the upstream.

Check it out https://candi.vercel.app 

Thanks for the access @agungdwiprasetyo, you may remove me from admin then.
